seed_everything: true
trainer:
  logger:
    class_path: lightning.pytorch.loggers.CSVLogger
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        patience: 5
        monitor: val_loss
  fast_dev_run: false
  max_epochs: 100
model:
  class_path: lightning_utils.lm_module.LmKeyClf
  init_args:
    model_classpath: models.HyperGT
    model_init_args:
      num_class: 30
      in_channels: 3
      num_of_heads: 4
    loss_fn_classpath: torch.nn.CrossEntropyLoss
    loss_fn_init_args: null
    id2label: clf_id2label
    label2id: clf_label2id
    lr: 0.001
data:
  delay: 4
  train_videos:
    - 'video_0'
    - 'video_1'
    - 'video_2'
    - 'video_3'
    - 'video_4'
    - 'video_5'
    - 'video_6'
  val_videos:
    - 'video_7'
    - 'video_8'
  test_videos: 
    - 'video_9'
    - 'video_10'
    - 'video_11'
  train_windows:
    - - 2
      - 2
    - - 3
      - 1
    - - 1
      - 3
  val_windows:
    - - 2
      - 2
  test_windows:
    - - 2
      - 2
  idle_gap: null
  batch_size: 32