seed_everything: true
trainer:
  logger:
    class_path: lightning.pytorch.loggers.CSVLogger
    init_args:
      save_dir: ctrgcn
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        patience: 10
        monitor: val_loss
  fast_dev_run: false
  max_epochs: 100
model:
  name: ctrgcn_clf
  model_classpath: models.CTRGCN
  model_init_args:
    num_point: 21
    num_person: 2
    graph: models.ctrgcn.hand_graph.Graph
    graph_args: 
      labeling_mode: spatial
  loss_fn_classpath: torch.nn.CrossEntropyLoss
  loss_fn_init_args: null
data:
  delay: 4
  train_videos: ['video_0', 'video_1', 'video_2', 'video_3', 'video_4', 
                  'video_5', 'video_6', 'video_7']
  val_videos: ['video_8', 'video_9']
  test_videos: ['video_10', 'video_11', 'video_12']
  idle_gap: null
  batch_size: 32