fit:
  seed_everything: true
  trainer:
    accelerator: gpu
    devices: [0, 1]
    logger:
      class_path: lightning.pytorch.loggers.CSVLogger
      init_args:
        save_dir: logs
    callbacks:
      - class_path: lightning.pytorch.callbacks.EarlyStopping
        init_args:
          patience: 10
          monitor: val_loss
    fast_dev_run: false
    max_epochs: 100
  model:
    model_name: resnet101_clf
    model_str: resnet101(sample_size=360, sample_duration=8, num_classes=len(clf_id2label))
    id2label: clf_id2label
    label2id: clf_label2id
  data:
    frames_dir: /kaggle/input/longvideo-1/low_raw_frames
    labels_dir: /kaggle/input/longvideo-1/labels
    train_videos: ['video_0']
    val_videos: ['video_1']
    test_videos: []
    idle_gap: null
    batch_size: 12
    num_workers: 4
    train_transforms: [
      'v2.RandomRotation(degrees=10)',
      'v2.RandomAdjustSharpness(sharpness_factor=2)'
    ]
    val_transforms: []
    test_transforms: []
  optimizer:
    class_path: torch.optim.Adam
    init_args:
      lr: 0.001
  ckpt_path: null