fit:
  seed_everything: true
  trainer:
    accelerator: gpu
    devices: [0, 1]
    logger:
      class_path: lightning.pytorch.loggers.CSVLogger
      init_args:
        save_dir: logs
    callbacks:
      - class_path: lightning.pytorch.callbacks.EarlyStopping
        init_args:
          patience: 10
          monitor: val_loss
    fast_dev_run: false
    max_epochs: 100
  model:
    model_name: resnet101_clf_a2_mixup
    model_str: resnet101(sample_size=224, sample_duration=8, num_classes=len(clf_id2label))
    id2label: clf_id2label
    label2id: clf_label2id
  data:
    frames_dir: /kaggle/input/angle-2/raw_frames_224
    labels_dir: /kaggle/input/angle-2/labels
    train_videos: ['video_0', 'video_1', 'video_3', 'video_4', 'video_5', 'video_6', 'video_7']
    val_videos: ['video_9']
    test_videos: []
    idle_gap: null
    batch_size: 12
    num_workers: 4
    train_collate_fns: ['mix_up_fn', 'color_zoom_fn']
    val_collate_fn: 'scale_fn'
    test_collate_fn: 'scale_fn'
  optimizer:
    class_path: torch.optim.Adam
    init_args:
      lr: 0.001
  ckpt_path: null
test:
  seed_everything: true
  trainer:
    accelerator: gpu
    devices: [0]
    logger:
      class_path: lightning.pytorch.loggers.CSVLogger
      init_args:
        save_dir: logs
    fast_dev_run: false
  model:
    model_name: resnet101_clf_a2_mixup
    model_str: resnet101(sample_size=224, sample_duration=8, num_classes=len(clf_id2label))
    id2label: clf_id2label
    label2id: clf_label2id
  data:
    frames_dir: /kaggle/input/angle-2/raw_frames_224
    labels_dir: /kaggle/input/angle-2/labels
    train_videos: []
    val_videos: []
    test_videos: ['video_8']
    idle_gap: null
    batch_size: 4
    num_workers: 4
    test_collate_fn: 'scale_fn'
  ckpt_path: null