seed_everything: true
trainer:
  logger:
    class_path: lightning.pytorch.loggers.CSVLogger
    init_args:
      save_dir: logs
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        patience: 5
        monitor: val_loss
  fast_dev_run: false
  max_epochs: 100
model:
  name: gcn_clf
  classpath: models.CTRGCN
  init_args:
    num_point: 21
    num_person: 2
    graph: models.ctrgcn.hand_graph.Graph
    graph_args: 
      labeling_mode: spatial
    num_class: 30
  id2label: clf_id2label
  label2id: clf_label2id
data:
  delay: 4
  train_videos: ['video_0', 'video_1', 'video_2', 'video_3', 'video_4']
  val_videos: ['video_5']
  test_videos: ['video_6', 'video_7']
  idle_gap: null