fit:
  seed_everything: true
  trainer:
    accelerator: cpu
    devices: auto
    logger:
      class_path: lightning.pytorch.loggers.CSVLogger
      init_args:
        save_dir: logs
    callbacks:
      - class_path: lightning.pytorch.callbacks.EarlyStopping
        init_args:
          patience: 10
          monitor: val_loss
    fast_dev_run: true
    max_epochs: 100
  model:
    model_name: resnet50_clf
    model_str: resnet50(sample_size=360, sample_duration=8, num_classes=len(detect_id2label))
    id2label: detect_id2label
    label2id: detect_label2id
  data:
    frames_dir: datasets/video/raw_frames
    labels_dir: datasets/video/labels
    delay: 4
    train_videos: ['video_0', 'video_1', 'video_2', 'video_3', 'video_4']
    val_videos: ['video_5']
    test_videos: ['video_6', 'video_7']
    idle_gap: 2
    batch_size: 8
    num_workers: 0
    train_transforms: [
      'v2.RandomRotation(degrees=10)',
      'v2.RandomAdjustSharpness(sharpness_factor=2)',
      'v2.RandomAdjustSharpness(sharpness_factor=2)',
      'v2.ColorJitter(brightness=(0.5,1.5),contrast=(1),saturation=(0.5,1.5),hue=(-0.1,0.1))',
    ]
    val_transforms: []
    test_transforms: []
  optimizer:
    class_path: torch.optim.Adam
    init_args:
      lr: 0.001
  ckpt_path: null
test:
  seed_everything: true
  trainer:
    accelerator: cpu
    devices: auto
    logger:
      class_path: lightning.pytorch.loggers.CSVLogger
      init_args:
        save_dir: logs
    fast_dev_run: true
  model:
    model_name: resnet50_detect
    model_str: resnet50(sample_size=360, sample_duration=8, num_classes=len(detect_id2label))
    id2label: detect_id2label
    label2id: detect_label2id
  data:
    frames_dir: datasets/video/raw_frames
    labels_dir: datasets/video/labels
    delay: 4
    train_videos: []
    val_videos: []
    test_videos: ['video_6', 'video_7']
    idle_gap: 2
    batch_size: 8
    num_workers: 0
    train_transforms: [
      'v2.RandomRotation(degrees=10)',
      'v2.RandomAdjustSharpness(sharpness_factor=2)',
      'v2.RandomAdjustSharpness(sharpness_factor=2)',
      'v2.ColorJitter(brightness=(0.5,1.5),contrast=(1),saturation=(0.5,1.5),hue=(-0.1,0.1))',
    ]
    val_transforms: []
    test_transforms: []
  ckpt_path: null