seed_everything: true
trainer:
  logger:
    class_path: lightning.pytorch.loggers.CSVLogger
    init_args:
      save_dir: infogcn
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        patience: 10
        monitor: val_loss
  fast_dev_run: false
  max_epochs: 100
model:
  name: infogcn
  model_classpath: models.SkateFormer
  model_init_args:
    num_points: 21
    num_classes: 30
    num_frames: 8
  loss_fn_classpath: torch.nn.CrossEntropyLoss
  loss_fn_init_args: null
  id2label: clf_id2label
  label2id: clf_label2id
data:
  delay: 4
  train_videos: ['video_0', 'video_1', 'video_2', 'video_3', 'video_4']
  val_videos: ['video_5']
  test_videos: ['video_6', 'video_7']
  idle_gap: null
  batch_size: 32